name: seg

channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults

dependencies:
  - python=3.10
  - pytorch=2.5.1
  - pytorch-cuda=12.1
  - numpy
  - scipy
  - matplotlib
  - pytest
  - monai
  - nibabel
  - tqdm
  - wandb
  - fastapi
  - uvicorn
  - python-multipart
  - portalocker
